sonar.projectKey=astiskala_lunch-buddy
sonar.organization=astiskala
sonar.projectName=lunch-buddy

# Source and test directories
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.integration.spec.ts
sonar.exclusions=src/test/**,src/environments/**,src/**/*.spec.ts,src/**/*.integration.spec.ts

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lunch-buddy/lcov.info

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.app.json
