/**
 * This file is auto-generated by tools/write-runtime-env.mjs.
 * Do not edit this file manually.
 */

<<<<<<< Updated upstream
export const runtimeEnv: Record<string, string | undefined> = {};
=======
export const runtimeEnv: Record<string, string | undefined> = {
    NG_APP_LUNCHMONEY_API_KEY: "mock-api-key-12345",
    NG_APP_LUNCHMONEY_API_BASE: "/v2",
};
>>>>>>> Stashed changes
