/**
 * This file is auto-generated by tools/write-runtime-env.mjs.
 * Do not edit this file manually.
 */

export const runtimeEnv: Record<string, string | undefined> = {
  NG_APP_LUNCHMONEY_API_BASE: "http://localhost:4600/v1",
};
